// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyProvider creates a new instance of MockKeyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyProvider {
	mock := &MockKeyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyProvider is an autogenerated mock type for the KeyProvider type
type MockKeyProvider struct {
	mock.Mock
}

type MockKeyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyProvider) EXPECT() *MockKeyProvider_Expecter {
	return &MockKeyProvider_Expecter{mock: &_m.Mock}
}

// Key provides a mock function for the type MockKeyProvider
func (_mock *MockKeyProvider) Key(context1 context.Context, s string, s1 string) (any, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (any, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) any); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyProvider_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type MockKeyProvider_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockKeyProvider_Expecter) Key(context1 interface{}, s interface{}, s1 interface{}) *MockKeyProvider_Key_Call {
	return &MockKeyProvider_Key_Call{Call: _e.mock.On("Key", context1, s, s1)}
}

func (_c *MockKeyProvider_Key_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockKeyProvider_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyProvider_Key_Call) Return(v any, err error) *MockKeyProvider_Key_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeyProvider_Key_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (any, error)) *MockKeyProvider_Key_Call {
	_c.Call.Return(run)
	return _c
}
