// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/beeemT/claimy/internal/claims"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type MockStore
func (_mock *MockStore) Acquire(context1 context.Context, actor claims.Actor, acquireRequest claims.AcquireRequest) (claims.AcquireResult, error) {
	ret := _mock.Called(context1, actor, acquireRequest)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 claims.AcquireResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.AcquireRequest) (claims.AcquireResult, error)); ok {
		return returnFunc(context1, actor, acquireRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.AcquireRequest) claims.AcquireResult); ok {
		r0 = returnFunc(context1, actor, acquireRequest)
	} else {
		r0 = ret.Get(0).(claims.AcquireResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, claims.Actor, claims.AcquireRequest) error); ok {
		r1 = returnFunc(context1, actor, acquireRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockStore_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - context1 context.Context
//   - actor claims.Actor
//   - acquireRequest claims.AcquireRequest
func (_e *MockStore_Expecter) Acquire(context1 interface{}, actor interface{}, acquireRequest interface{}) *MockStore_Acquire_Call {
	return &MockStore_Acquire_Call{Call: _e.mock.On("Acquire", context1, actor, acquireRequest)}
}

func (_c *MockStore_Acquire_Call) Run(run func(context1 context.Context, actor claims.Actor, acquireRequest claims.AcquireRequest)) *MockStore_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 claims.Actor
		if args[1] != nil {
			arg1 = args[1].(claims.Actor)
		}
		var arg2 claims.AcquireRequest
		if args[2] != nil {
			arg2 = args[2].(claims.AcquireRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Acquire_Call) Return(acquireResult claims.AcquireResult, err error) *MockStore_Acquire_Call {
	_c.Call.Return(acquireResult, err)
	return _c
}

func (_c *MockStore_Acquire_Call) RunAndReturn(run func(context1 context.Context, actor claims.Actor, acquireRequest claims.AcquireRequest) (claims.AcquireResult, error)) *MockStore_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeExpiry provides a mock function for the type MockStore
func (_mock *MockStore) ChangeExpiry(context1 context.Context, actor claims.Actor, expiryRequest claims.ExpiryRequest) (claims.MutationResult, error) {
	ret := _mock.Called(context1, actor, expiryRequest)

	if len(ret) == 0 {
		panic("no return value specified for ChangeExpiry")
	}

	var r0 claims.MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.ExpiryRequest) (claims.MutationResult, error)); ok {
		return returnFunc(context1, actor, expiryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.ExpiryRequest) claims.MutationResult); ok {
		r0 = returnFunc(context1, actor, expiryRequest)
	} else {
		r0 = ret.Get(0).(claims.MutationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, claims.Actor, claims.ExpiryRequest) error); ok {
		r1 = returnFunc(context1, actor, expiryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ChangeExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeExpiry'
type MockStore_ChangeExpiry_Call struct {
	*mock.Call
}

// ChangeExpiry is a helper method to define mock.On call
//   - context1 context.Context
//   - actor claims.Actor
//   - expiryRequest claims.ExpiryRequest
func (_e *MockStore_Expecter) ChangeExpiry(context1 interface{}, actor interface{}, expiryRequest interface{}) *MockStore_ChangeExpiry_Call {
	return &MockStore_ChangeExpiry_Call{Call: _e.mock.On("ChangeExpiry", context1, actor, expiryRequest)}
}

func (_c *MockStore_ChangeExpiry_Call) Run(run func(context1 context.Context, actor claims.Actor, expiryRequest claims.ExpiryRequest)) *MockStore_ChangeExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 claims.Actor
		if args[1] != nil {
			arg1 = args[1].(claims.Actor)
		}
		var arg2 claims.ExpiryRequest
		if args[2] != nil {
			arg2 = args[2].(claims.ExpiryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_ChangeExpiry_Call) Return(mutationResult claims.MutationResult, err error) *MockStore_ChangeExpiry_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *MockStore_ChangeExpiry_Call) RunAndReturn(run func(context1 context.Context, actor claims.Actor, expiryRequest claims.ExpiryRequest) (claims.MutationResult, error)) *MockStore_ChangeExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type MockStore
func (_mock *MockStore) Prune(context1 context.Context) (claims.PruneResult, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 claims.PruneResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (claims.PruneResult, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) claims.PruneResult); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(claims.PruneResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockStore_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockStore_Expecter) Prune(context1 interface{}) *MockStore_Prune_Call {
	return &MockStore_Prune_Call{Call: _e.mock.On("Prune", context1)}
}

func (_c *MockStore_Prune_Call) Run(run func(context1 context.Context)) *MockStore_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Prune_Call) Return(pruneResult claims.PruneResult, err error) *MockStore_Prune_Call {
	_c.Call.Return(pruneResult, err)
	return _c
}

func (_c *MockStore_Prune_Call) RunAndReturn(run func(context1 context.Context) (claims.PruneResult, error)) *MockStore_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStore
func (_mock *MockStore) Query(context1 context.Context, actor claims.Actor, queryRequest claims.QueryRequest) (claims.QueryResult, error) {
	ret := _mock.Called(context1, actor, queryRequest)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 claims.QueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.QueryRequest) (claims.QueryResult, error)); ok {
		return returnFunc(context1, actor, queryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.QueryRequest) claims.QueryResult); ok {
		r0 = returnFunc(context1, actor, queryRequest)
	} else {
		r0 = ret.Get(0).(claims.QueryResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, claims.Actor, claims.QueryRequest) error); ok {
		r1 = returnFunc(context1, actor, queryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStore_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - context1 context.Context
//   - actor claims.Actor
//   - queryRequest claims.QueryRequest
func (_e *MockStore_Expecter) Query(context1 interface{}, actor interface{}, queryRequest interface{}) *MockStore_Query_Call {
	return &MockStore_Query_Call{Call: _e.mock.On("Query", context1, actor, queryRequest)}
}

func (_c *MockStore_Query_Call) Run(run func(context1 context.Context, actor claims.Actor, queryRequest claims.QueryRequest)) *MockStore_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 claims.Actor
		if args[1] != nil {
			arg1 = args[1].(claims.Actor)
		}
		var arg2 claims.QueryRequest
		if args[2] != nil {
			arg2 = args[2].(claims.QueryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Query_Call) Return(queryResult claims.QueryResult, err error) *MockStore_Query_Call {
	_c.Call.Return(queryResult, err)
	return _c
}

func (_c *MockStore_Query_Call) RunAndReturn(run func(context1 context.Context, actor claims.Actor, queryRequest claims.QueryRequest) (claims.QueryResult, error)) *MockStore_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockStore
func (_mock *MockStore) Release(context1 context.Context, actor claims.Actor, releaseRequest claims.ReleaseRequest) (claims.MutationResult, error) {
	ret := _mock.Called(context1, actor, releaseRequest)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 claims.MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.ReleaseRequest) (claims.MutationResult, error)); ok {
		return returnFunc(context1, actor, releaseRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, claims.Actor, claims.ReleaseRequest) claims.MutationResult); ok {
		r0 = returnFunc(context1, actor, releaseRequest)
	} else {
		r0 = ret.Get(0).(claims.MutationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, claims.Actor, claims.ReleaseRequest) error); ok {
		r1 = returnFunc(context1, actor, releaseRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockStore_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - context1 context.Context
//   - actor claims.Actor
//   - releaseRequest claims.ReleaseRequest
func (_e *MockStore_Expecter) Release(context1 interface{}, actor interface{}, releaseRequest interface{}) *MockStore_Release_Call {
	return &MockStore_Release_Call{Call: _e.mock.On("Release", context1, actor, releaseRequest)}
}

func (_c *MockStore_Release_Call) Run(run func(context1 context.Context, actor claims.Actor, releaseRequest claims.ReleaseRequest)) *MockStore_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 claims.Actor
		if args[1] != nil {
			arg1 = args[1].(claims.Actor)
		}
		var arg2 claims.ReleaseRequest
		if args[2] != nil {
			arg2 = args[2].(claims.ReleaseRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Release_Call) Return(mutationResult claims.MutationResult, err error) *MockStore_Release_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *MockStore_Release_Call) RunAndReturn(run func(context1 context.Context, actor claims.Actor, releaseRequest claims.ReleaseRequest) (claims.MutationResult, error)) *MockStore_Release_Call {
	_c.Call.Return(run)
	return _c
}
