// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for Environment.
const (
	Prod    Environment = "prod"
	Sandbox Environment = "sandbox"
)

// Defines values for ErrorDetailCode.
const (
	ErrorDetailCodeConflict           ErrorDetailCode = "conflict"
	ErrorDetailCodeForbidden          ErrorDetailCode = "forbidden"
	ErrorDetailCodeHistoryUnavailable ErrorDetailCode = "history_unavailable"
	ErrorDetailCodeInvalidRequest     ErrorDetailCode = "invalid_request"
	ErrorDetailCodeNotFound           ErrorDetailCode = "not_found"
	ErrorDetailCodeStorageError       ErrorDetailCode = "storage_error"
	ErrorDetailCodeUnauthenticated    ErrorDetailCode = "unauthenticated"
)

// Defines values for Source.
const (
	Ci     Source = "ci"
	Manual Source = "manual"
)

// AcquireRequest defines model for AcquireRequest.
type AcquireRequest struct {
	App          *string       `json:"app,omitempty"`
	Environments []Environment `json:"environments"`
	ExpiresAt    *time.Time    `json:"expiresAt,omitempty"`
	Group        string        `json:"group"`
	RequestId    string        `json:"requestId"`
}

// AcquireResponse defines model for AcquireResponse.
type AcquireResponse struct {
	Acquired  bool        `json:"acquired"`
	Claim     *Claim      `json:"claim,omitempty"`
	Conflicts *[]Conflict `json:"conflicts,omitempty"`
}

// CatalogApp defines model for CatalogApp.
type CatalogApp struct {
	CanonicalName string    `json:"canonicalName"`
	CreatedAt     time.Time `json:"createdAt"`
	GroupId       string    `json:"groupId"`
	Id            string    `json:"id"`
}

// CatalogAppsResponse defines model for CatalogAppsResponse.
type CatalogAppsResponse struct {
	Results []CatalogApp `json:"results"`
	Total   int64        `json:"total"`
}

// CatalogFilter defines model for CatalogFilter.
type CatalogFilter struct {
	CanonicalName *string `json:"canonicalName,omitempty"`
}

// CatalogGroup defines model for CatalogGroup.
type CatalogGroup struct {
	CanonicalName string    `json:"canonicalName"`
	CreatedAt     time.Time `json:"createdAt"`
	Id            string    `json:"id"`
}

// CatalogGroupsResponse defines model for CatalogGroupsResponse.
type CatalogGroupsResponse struct {
	Results []CatalogGroup `json:"results"`
	Total   int64          `json:"total"`
}

// CatalogListRequest defines model for CatalogListRequest.
type CatalogListRequest struct {
	Filter *CatalogFilter `json:"filter,omitempty"`
	Page   *CatalogPage   `json:"page,omitempty"`
}

// CatalogPage defines model for CatalogPage.
type CatalogPage struct {
	Limit  *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

// Claim defines model for Claim.
type Claim struct {
	ActiveNow    bool                `json:"activeNow"`
	CreatedAt    time.Time           `json:"createdAt"`
	Environments []Environment       `json:"environments"`
	ExpiresAt    time.Time           `json:"expiresAt"`
	Gitlab       *GitLabIdentity     `json:"gitlab,omitempty"`
	Id           openapi_types.UUID  `json:"id"`
	Inherited    bool                `json:"inherited"`
	OwnerEmail   openapi_types.Email `json:"ownerEmail"`
	ReleasedAt   *time.Time          `json:"releasedAt,omitempty"`
	Revision     int64               `json:"revision"`
	Scope        Scope               `json:"scope"`
	Source       Source              `json:"source"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Environments []Environment       `json:"environments"`
	ExpiresAt    time.Time           `json:"expiresAt"`
	Id           openapi_types.UUID  `json:"id"`
	OwnerEmail   openapi_types.Email `json:"ownerEmail"`
	Scope        Scope               `json:"scope"`
	Source       Source              `json:"source"`
}

// Environment defines model for Environment.
type Environment string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    ErrorDetailCode `json:"code"`
	Message string          `json:"message"`
	Status  int32           `json:"status"`
}

// ErrorDetailCode defines model for ErrorDetail.Code.
type ErrorDetailCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ExpiryRequest defines model for ExpiryRequest.
type ExpiryRequest struct {
	ExpectedRevision int64     `json:"expectedRevision"`
	ExpiresAt        time.Time `json:"expiresAt"`
	RequestId        string    `json:"requestId"`
}

// GitLabIdentity defines model for GitLabIdentity.
type GitLabIdentity struct {
	Issuer    string `json:"issuer"`
	JobId     string `json:"jobId"`
	ProjectId string `json:"projectId"`
	UserId    string `json:"userId"`
}

// MutationRequest defines model for MutationRequest.
type MutationRequest struct {
	RequestId string `json:"requestId"`
}

// MutationResponse defines model for MutationResponse.
type MutationResponse struct {
	Changed bool  `json:"changed"`
	Claim   Claim `json:"claim"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	App          *string        `json:"app,omitempty"`
	At           *time.Time     `json:"at,omitempty"`
	Environments *[]Environment `json:"environments,omitempty"`
	Group        string         `json:"group"`
}

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	AllowedForCaller bool      `json:"allowedForCaller"`
	At               time.Time `json:"at"`
	Claims           []Claim   `json:"claims"`
	Free             bool      `json:"free"`
	Known            bool      `json:"known"`
	Projected        bool      `json:"projected"`
}

// Scope defines model for Scope.
type Scope struct {
	App   *string `json:"app,omitempty"`
	Group string  `json:"group"`
}

// Source defines model for Source.
type Source string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// ConflictResponse defines model for ConflictResponse.
type ConflictResponse = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// HistoryUnavailable defines model for HistoryUnavailable.
type HistoryUnavailable = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServerError defines model for ServerError.
type ServerError = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListCatalogGroupsJSONRequestBody defines body for ListCatalogGroups for application/json ContentType.
type ListCatalogGroupsJSONRequestBody = CatalogListRequest

// ListCatalogAppsJSONRequestBody defines body for ListCatalogApps for application/json ContentType.
type ListCatalogAppsJSONRequestBody = CatalogListRequest

// AcquireClaimJSONRequestBody defines body for AcquireClaim for application/json ContentType.
type AcquireClaimJSONRequestBody = AcquireRequest

// QueryClaimsJSONRequestBody defines body for QueryClaims for application/json ContentType.
type QueryClaimsJSONRequestBody = QueryRequest

// ChangeClaimExpiryJSONRequestBody defines body for ChangeClaimExpiry for application/json ContentType.
type ChangeClaimExpiryJSONRequestBody = ExpiryRequest

// ReleaseClaimJSONRequestBody defines body for ReleaseClaim for application/json ContentType.
type ReleaseClaimJSONRequestBody = MutationRequest
