// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for Environment.
const (
	Prod    Environment = "prod"
	Sandbox Environment = "sandbox"
)

// Defines values for ErrorDetailCode.
const (
	ErrorDetailCodeConflict           ErrorDetailCode = "conflict"
	ErrorDetailCodeForbidden          ErrorDetailCode = "forbidden"
	ErrorDetailCodeHistoryUnavailable ErrorDetailCode = "history_unavailable"
	ErrorDetailCodeInvalidRequest     ErrorDetailCode = "invalid_request"
	ErrorDetailCodeNotFound           ErrorDetailCode = "not_found"
	ErrorDetailCodeStorageError       ErrorDetailCode = "storage_error"
	ErrorDetailCodeUnauthenticated    ErrorDetailCode = "unauthenticated"
)

// Defines values for Source.
const (
	Ci     Source = "ci"
	Manual Source = "manual"
)

// AcquireRequest defines model for AcquireRequest.
type AcquireRequest struct {
	App          *string       `json:"app,omitempty"`
	Environments []Environment `json:"environments"`
	ExpiresAt    *time.Time    `json:"expiresAt,omitempty"`
	Group        string        `json:"group"`
	RequestId    string        `json:"requestId"`
}

// AcquireResponse defines model for AcquireResponse.
type AcquireResponse struct {
	Acquired  bool        `json:"acquired"`
	Claim     *Claim      `json:"claim,omitempty"`
	Conflicts *[]Conflict `json:"conflicts,omitempty"`
}

// CatalogApp defines model for CatalogApp.
type CatalogApp struct {
	CanonicalName string    `json:"canonicalName"`
	CreatedAt     time.Time `json:"createdAt"`
	GroupId       string    `json:"groupId"`
	Id            string    `json:"id"`
}

// CatalogAppsResponse defines model for CatalogAppsResponse.
type CatalogAppsResponse struct {
	Results []CatalogApp `json:"results"`
	Total   int64        `json:"total"`
}

// CatalogFilter defines model for CatalogFilter.
type CatalogFilter struct {
	CanonicalName *string `json:"canonicalName,omitempty"`
}

// CatalogGroup defines model for CatalogGroup.
type CatalogGroup struct {
	CanonicalName string    `json:"canonicalName"`
	CreatedAt     time.Time `json:"createdAt"`
	Id            string    `json:"id"`
}

// CatalogGroupsResponse defines model for CatalogGroupsResponse.
type CatalogGroupsResponse struct {
	Results []CatalogGroup `json:"results"`
	Total   int64          `json:"total"`
}

// CatalogListRequest defines model for CatalogListRequest.
type CatalogListRequest struct {
	Filter *CatalogFilter `json:"filter,omitempty"`
	Page   *CatalogPage   `json:"page,omitempty"`
}

// CatalogPage defines model for CatalogPage.
type CatalogPage struct {
	Limit  *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

// Claim defines model for Claim.
type Claim struct {
	ActiveNow    bool                `json:"activeNow"`
	CreatedAt    time.Time           `json:"createdAt"`
	Environments []Environment       `json:"environments"`
	ExpiresAt    time.Time           `json:"expiresAt"`
	Gitlab       *GitLabIdentity     `json:"gitlab,omitempty"`
	Id           openapi_types.UUID  `json:"id"`
	Inherited    bool                `json:"inherited"`
	OwnerEmail   openapi_types.Email `json:"ownerEmail"`
	ReleasedAt   *time.Time          `json:"releasedAt,omitempty"`
	Revision     int64               `json:"revision"`
	Scope        Scope               `json:"scope"`
	Source       Source              `json:"source"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Environments []Environment       `json:"environments"`
	ExpiresAt    time.Time           `json:"expiresAt"`
	Id           openapi_types.UUID  `json:"id"`
	OwnerEmail   openapi_types.Email `json:"ownerEmail"`
	Scope        Scope               `json:"scope"`
	Source       Source              `json:"source"`
}

// Environment defines model for Environment.
type Environment string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    ErrorDetailCode `json:"code"`
	Message string          `json:"message"`
	Status  int32           `json:"status"`
}

// ErrorDetailCode defines model for ErrorDetail.Code.
type ErrorDetailCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ExpiryRequest defines model for ExpiryRequest.
type ExpiryRequest struct {
	ExpectedRevision int64     `json:"expectedRevision"`
	ExpiresAt        time.Time `json:"expiresAt"`
	RequestId        string    `json:"requestId"`
}

// GitLabIdentity defines model for GitLabIdentity.
type GitLabIdentity struct {
	Issuer    string `json:"issuer"`
	JobId     string `json:"jobId"`
	ProjectId string `json:"projectId"`
	UserId    string `json:"userId"`
}

// MutationRequest defines model for MutationRequest.
type MutationRequest struct {
	RequestId string `json:"requestId"`
}

// MutationResponse defines model for MutationResponse.
type MutationResponse struct {
	Changed bool  `json:"changed"`
	Claim   Claim `json:"claim"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	App          *string        `json:"app,omitempty"`
	At           *time.Time     `json:"at,omitempty"`
	Environments *[]Environment `json:"environments,omitempty"`
	Group        string         `json:"group"`
}

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	AllowedForCaller bool      `json:"allowedForCaller"`
	At               time.Time `json:"at"`
	Claims           []Claim   `json:"claims"`
	Free             bool      `json:"free"`
	Known            bool      `json:"known"`
	Projected        bool      `json:"projected"`
}

// Scope defines model for Scope.
type Scope struct {
	App   *string `json:"app,omitempty"`
	Group string  `json:"group"`
}

// Source defines model for Source.
type Source string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// ConflictResponse defines model for ConflictResponse.
type ConflictResponse = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// HistoryUnavailable defines model for HistoryUnavailable.
type HistoryUnavailable = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServerError defines model for ServerError.
type ServerError = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListCatalogGroupsJSONRequestBody defines body for ListCatalogGroups for application/json ContentType.
type ListCatalogGroupsJSONRequestBody = CatalogListRequest

// ListCatalogAppsJSONRequestBody defines body for ListCatalogApps for application/json ContentType.
type ListCatalogAppsJSONRequestBody = CatalogListRequest

// AcquireClaimJSONRequestBody defines body for AcquireClaim for application/json ContentType.
type AcquireClaimJSONRequestBody = AcquireRequest

// QueryClaimsJSONRequestBody defines body for QueryClaims for application/json ContentType.
type QueryClaimsJSONRequestBody = QueryRequest

// ChangeClaimExpiryJSONRequestBody defines body for ChangeClaimExpiry for application/json ContentType.
type ChangeClaimExpiryJSONRequestBody = ExpiryRequest

// ReleaseClaimJSONRequestBody defines body for ReleaseClaim for application/json ContentType.
type ReleaseClaimJSONRequestBody = MutationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListCatalogGroupsWithBody request with any body
	ListCatalogGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListCatalogGroups(ctx context.Context, body ListCatalogGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCatalogGroup request
	GetCatalogGroup(ctx context.Context, groupSlug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCatalogAppsWithBody request with any body
	ListCatalogAppsWithBody(ctx context.Context, groupSlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListCatalogApps(ctx context.Context, groupSlug string, body ListCatalogAppsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AcquireClaimWithBody request with any body
	AcquireClaimWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AcquireClaim(ctx context.Context, body AcquireClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// QueryClaimsWithBody request with any body
	QueryClaimsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	QueryClaims(ctx context.Context, body QueryClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChangeClaimExpiryWithBody request with any body
	ChangeClaimExpiryWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChangeClaimExpiry(ctx context.Context, id openapi_types.UUID, body ChangeClaimExpiryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReleaseClaimWithBody request with any body
	ReleaseClaimWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReleaseClaim(ctx context.Context, id openapi_types.UUID, body ReleaseClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListCatalogGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCatalogGroupsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCatalogGroups(ctx context.Context, body ListCatalogGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCatalogGroupsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCatalogGroup(ctx context.Context, groupSlug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCatalogGroupRequest(c.Server, groupSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCatalogAppsWithBody(ctx context.Context, groupSlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCatalogAppsRequestWithBody(c.Server, groupSlug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCatalogApps(ctx context.Context, groupSlug string, body ListCatalogAppsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCatalogAppsRequest(c.Server, groupSlug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AcquireClaimWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAcquireClaimRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AcquireClaim(ctx context.Context, body AcquireClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAcquireClaimRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryClaimsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryClaimsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryClaims(ctx context.Context, body QueryClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryClaimsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeClaimExpiryWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeClaimExpiryRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeClaimExpiry(ctx context.Context, id openapi_types.UUID, body ChangeClaimExpiryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeClaimExpiryRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseClaimWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseClaimRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseClaim(ctx context.Context, id openapi_types.UUID, body ReleaseClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseClaimRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCatalogGroupsRequest calls the generic ListCatalogGroups builder with application/json body
func NewListCatalogGroupsRequest(server string, body ListCatalogGroupsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListCatalogGroupsRequestWithBody(server, "application/json", bodyReader)
}

// NewListCatalogGroupsRequestWithBody generates requests for ListCatalogGroups with any type of body
func NewListCatalogGroupsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/catalog/groups/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCatalogGroupRequest generates requests for GetCatalogGroup
func NewGetCatalogGroupRequest(server string, groupSlug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupSlug", runtime.ParamLocationPath, groupSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/catalog/groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCatalogAppsRequest calls the generic ListCatalogApps builder with application/json body
func NewListCatalogAppsRequest(server string, groupSlug string, body ListCatalogAppsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListCatalogAppsRequestWithBody(server, groupSlug, "application/json", bodyReader)
}

// NewListCatalogAppsRequestWithBody generates requests for ListCatalogApps with any type of body
func NewListCatalogAppsRequestWithBody(server string, groupSlug string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "groupSlug", runtime.ParamLocationPath, groupSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/catalog/groups/%s/apps/query", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAcquireClaimRequest calls the generic AcquireClaim builder with application/json body
func NewAcquireClaimRequest(server string, body AcquireClaimJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAcquireClaimRequestWithBody(server, "application/json", bodyReader)
}

// NewAcquireClaimRequestWithBody generates requests for AcquireClaim with any type of body
func NewAcquireClaimRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/claims/acquire")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewQueryClaimsRequest calls the generic QueryClaims builder with application/json body
func NewQueryClaimsRequest(server string, body QueryClaimsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewQueryClaimsRequestWithBody(server, "application/json", bodyReader)
}

// NewQueryClaimsRequestWithBody generates requests for QueryClaims with any type of body
func NewQueryClaimsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/claims/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewChangeClaimExpiryRequest calls the generic ChangeClaimExpiry builder with application/json body
func NewChangeClaimExpiryRequest(server string, id openapi_types.UUID, body ChangeClaimExpiryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChangeClaimExpiryRequestWithBody(server, id, "application/json", bodyReader)
}

// NewChangeClaimExpiryRequestWithBody generates requests for ChangeClaimExpiry with any type of body
func NewChangeClaimExpiryRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/claims/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReleaseClaimRequest calls the generic ReleaseClaim builder with application/json body
func NewReleaseClaimRequest(server string, id openapi_types.UUID, body ReleaseClaimJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReleaseClaimRequestWithBody(server, id, "application/json", bodyReader)
}

// NewReleaseClaimRequestWithBody generates requests for ReleaseClaim with any type of body
func NewReleaseClaimRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/claims/%s/release", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListCatalogGroupsWithBodyWithResponse request with any body
	ListCatalogGroupsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListCatalogGroupsResponse, error)

	ListCatalogGroupsWithResponse(ctx context.Context, body ListCatalogGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListCatalogGroupsResponse, error)

	// GetCatalogGroupWithResponse request
	GetCatalogGroupWithResponse(ctx context.Context, groupSlug string, reqEditors ...RequestEditorFn) (*GetCatalogGroupResponse, error)

	// ListCatalogAppsWithBodyWithResponse request with any body
	ListCatalogAppsWithBodyWithResponse(ctx context.Context, groupSlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListCatalogAppsResponse, error)

	ListCatalogAppsWithResponse(ctx context.Context, groupSlug string, body ListCatalogAppsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListCatalogAppsResponse, error)

	// AcquireClaimWithBodyWithResponse request with any body
	AcquireClaimWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AcquireClaimResponse, error)

	AcquireClaimWithResponse(ctx context.Context, body AcquireClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*AcquireClaimResponse, error)

	// QueryClaimsWithBodyWithResponse request with any body
	QueryClaimsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryClaimsResponse, error)

	QueryClaimsWithResponse(ctx context.Context, body QueryClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryClaimsResponse, error)

	// ChangeClaimExpiryWithBodyWithResponse request with any body
	ChangeClaimExpiryWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeClaimExpiryResponse, error)

	ChangeClaimExpiryWithResponse(ctx context.Context, id openapi_types.UUID, body ChangeClaimExpiryJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeClaimExpiryResponse, error)

	// ReleaseClaimWithBodyWithResponse request with any body
	ReleaseClaimWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReleaseClaimResponse, error)

	ReleaseClaimWithResponse(ctx context.Context, id openapi_types.UUID, body ReleaseClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*ReleaseClaimResponse, error)
}

type ListCatalogGroupsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CatalogGroupsResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r ListCatalogGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCatalogGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCatalogGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CatalogGroup
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r GetCatalogGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCatalogGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListCatalogAppsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CatalogAppsResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r ListCatalogAppsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCatalogAppsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AcquireClaimResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AcquireResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON409      *ConflictResponse
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r AcquireClaimResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AcquireClaimResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type QueryClaimsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QueryResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON410      *HistoryUnavailable
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r QueryClaimsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryClaimsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChangeClaimExpiryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MutationResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *ConflictResponse
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r ChangeClaimExpiryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangeClaimExpiryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReleaseClaimResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MutationResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *ConflictResponse
	JSON500      *ServerError
}

// Status returns HTTPResponse.Status
func (r ReleaseClaimResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReleaseClaimResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListCatalogGroupsWithBodyWithResponse request with arbitrary body returning *ListCatalogGroupsResponse
func (c *ClientWithResponses) ListCatalogGroupsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListCatalogGroupsResponse, error) {
	rsp, err := c.ListCatalogGroupsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCatalogGroupsResponse(rsp)
}

func (c *ClientWithResponses) ListCatalogGroupsWithResponse(ctx context.Context, body ListCatalogGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListCatalogGroupsResponse, error) {
	rsp, err := c.ListCatalogGroups(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCatalogGroupsResponse(rsp)
}

// GetCatalogGroupWithResponse request returning *GetCatalogGroupResponse
func (c *ClientWithResponses) GetCatalogGroupWithResponse(ctx context.Context, groupSlug string, reqEditors ...RequestEditorFn) (*GetCatalogGroupResponse, error) {
	rsp, err := c.GetCatalogGroup(ctx, groupSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCatalogGroupResponse(rsp)
}

// ListCatalogAppsWithBodyWithResponse request with arbitrary body returning *ListCatalogAppsResponse
func (c *ClientWithResponses) ListCatalogAppsWithBodyWithResponse(ctx context.Context, groupSlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListCatalogAppsResponse, error) {
	rsp, err := c.ListCatalogAppsWithBody(ctx, groupSlug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCatalogAppsResponse(rsp)
}

func (c *ClientWithResponses) ListCatalogAppsWithResponse(ctx context.Context, groupSlug string, body ListCatalogAppsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListCatalogAppsResponse, error) {
	rsp, err := c.ListCatalogApps(ctx, groupSlug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCatalogAppsResponse(rsp)
}

// AcquireClaimWithBodyWithResponse request with arbitrary body returning *AcquireClaimResponse
func (c *ClientWithResponses) AcquireClaimWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AcquireClaimResponse, error) {
	rsp, err := c.AcquireClaimWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAcquireClaimResponse(rsp)
}

func (c *ClientWithResponses) AcquireClaimWithResponse(ctx context.Context, body AcquireClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*AcquireClaimResponse, error) {
	rsp, err := c.AcquireClaim(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAcquireClaimResponse(rsp)
}

// QueryClaimsWithBodyWithResponse request with arbitrary body returning *QueryClaimsResponse
func (c *ClientWithResponses) QueryClaimsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryClaimsResponse, error) {
	rsp, err := c.QueryClaimsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryClaimsResponse(rsp)
}

func (c *ClientWithResponses) QueryClaimsWithResponse(ctx context.Context, body QueryClaimsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryClaimsResponse, error) {
	rsp, err := c.QueryClaims(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryClaimsResponse(rsp)
}

// ChangeClaimExpiryWithBodyWithResponse request with arbitrary body returning *ChangeClaimExpiryResponse
func (c *ClientWithResponses) ChangeClaimExpiryWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeClaimExpiryResponse, error) {
	rsp, err := c.ChangeClaimExpiryWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeClaimExpiryResponse(rsp)
}

func (c *ClientWithResponses) ChangeClaimExpiryWithResponse(ctx context.Context, id openapi_types.UUID, body ChangeClaimExpiryJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeClaimExpiryResponse, error) {
	rsp, err := c.ChangeClaimExpiry(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeClaimExpiryResponse(rsp)
}

// ReleaseClaimWithBodyWithResponse request with arbitrary body returning *ReleaseClaimResponse
func (c *ClientWithResponses) ReleaseClaimWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReleaseClaimResponse, error) {
	rsp, err := c.ReleaseClaimWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseClaimResponse(rsp)
}

func (c *ClientWithResponses) ReleaseClaimWithResponse(ctx context.Context, id openapi_types.UUID, body ReleaseClaimJSONRequestBody, reqEditors ...RequestEditorFn) (*ReleaseClaimResponse, error) {
	rsp, err := c.ReleaseClaim(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseClaimResponse(rsp)
}

// ParseListCatalogGroupsResponse parses an HTTP response from a ListCatalogGroupsWithResponse call
func ParseListCatalogGroupsResponse(rsp *http.Response) (*ListCatalogGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCatalogGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CatalogGroupsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetCatalogGroupResponse parses an HTTP response from a GetCatalogGroupWithResponse call
func ParseGetCatalogGroupResponse(rsp *http.Response) (*GetCatalogGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCatalogGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CatalogGroup
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListCatalogAppsResponse parses an HTTP response from a ListCatalogAppsWithResponse call
func ParseListCatalogAppsResponse(rsp *http.Response) (*ListCatalogAppsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCatalogAppsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CatalogAppsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAcquireClaimResponse parses an HTTP response from a AcquireClaimWithResponse call
func ParseAcquireClaimResponse(rsp *http.Response) (*AcquireClaimResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AcquireClaimResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AcquireResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseQueryClaimsResponse parses an HTTP response from a QueryClaimsWithResponse call
func ParseQueryClaimsResponse(rsp *http.Response) (*QueryClaimsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryClaimsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QueryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 410:
		var dest HistoryUnavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON410 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseChangeClaimExpiryResponse parses an HTTP response from a ChangeClaimExpiryWithResponse call
func ParseChangeClaimExpiryResponse(rsp *http.Response) (*ChangeClaimExpiryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangeClaimExpiryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MutationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseReleaseClaimResponse parses an HTTP response from a ReleaseClaimWithResponse call
func ParseReleaseClaimResponse(rsp *http.Response) (*ReleaseClaimResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReleaseClaimResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MutationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
